algoritmo "SomaFuncao"
// Função :
// Autor :
// Data : 08/05/2024
// Seção de Declarações 
var
   V1, V2, S: Inteiro
Funcao Soma(X, Y: Inteiro): Inteiro

inicio
      Retorne X + Y
FimFuncao

inicio
// Seção de Comandos
   Escreva("Digite o primeiro valor: ")
   Leia(V1)
   Escreva("Digite o segundo valor: ")
   Leia (V2)
   S <- Soma(V1, V2)
   EscrevaL ("A soma entre ", V1, " e ", V2, " e igual a ", S)
   
fimalgoritmo
