algoritmo "Emprestimocreusa"
// Função :
// Autor :
// Data : 24/05/2024
// Seção de Declarações 
var
   q, j, p, v, t:Real

inicio
      Escreva ("Qual é o valo do emprestimo? ")
      Leia(v)
      Escreva ("Quanto de juros ? ")
      Leia (j)
      Escreva ("Quantas parcelas ?")
      Leia (p)
      q <- v / p + j
      EscrevaL("Vou pagar ", P, " parcelas de R$ ", q," ")
       t <- j * p + v
      Escreva ("valor total com juros", t,"")
      
// Seção de Comandos 
fimalgoritmo


